import React, { useState, useEffect } from 'react';
import api from '../../api/api';
import Message from '../../components/Message';
import '../style/BillHistory.css'

const BillHistory = ({ restaurantId }) => {
    const [bills, setBills] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [filter, setFilter] = useState('all'); // all, year, month, last60, last30, last7, thisWeek

    useEffect(() => {
        if (restaurantId) {
            fetchBills();
        }
    }, [restaurantId, filter]);

    const fetchBills = async () => {
        setLoading(true);
        setError(null);
        try {
            let url = `/bills/restaurant/${restaurantId}`;
            if (filter !== 'all') {
                url += `?filter=${filter}`;
            }
            const res = await api.get(url);
            setBills(res.data);
        } catch (err) {
            setError(err.response?.data?.message || err.message);
        } finally {
            setLoading(false);
        }
    };

    if (loading) return <div className="text-center p-8">Loading bill history...</div>;
    if (error) return <div className="text-center p-8 text-red-500">Error: {error}</div>;

    return (
        <div className="bill-history-container">
            <h2 className="bill-heading">Bill History</h2>
            <div className="filter-group">
                <select
                    value={filter}
                    onChange={(e) => setFilter(e.target.value)}
                    className="filter-select"
                >
                    <option value="all">All Time</option>
                    <option value="last7">Last 7 Days</option>
                    <option value="last30">Last 30 Days</option>
                    <option value="last60">Last 60 Days</option>
                    <option value="thisWeek">This Week</option>
                    <option value="month">This Month</option>
                    <option value="year">This Year</option>
                </select>
                <button onClick={fetchBills} className="filter-button">Apply Filter</button>
            </div>
            <Message type={error ? 'error' : 'success'} message={error} />

            {bills.length === 0 ? (
                <p className="empty-message">No bills found for the selected period.</p>
            ) : (
                <div className="table-container">
                    <table className="bill-table">
                        <thead>
                            <tr className="table-header">
                                <th className="table-cell table-cell-left">Bill ID</th>
                                <th className="table-cell table-cell-left">Table No.</th>
                                <th className="table-cell table-cell-left">Customer</th>
                                <th className="table-cell table-cell-left">Date</th>
                                <th className="table-cell table-cell-right">Total (excl. Tax)</th>
                                <th className="table-cell table-cell-right">GST (%)</th>
                                <th className="table-cell table-cell-right">Total (incl. Tax)</th>
                                <th className="table-cell table-cell-center">Generated By</th>
                            </tr>
                        </thead>
                        <tbody>
                            {bills.map((bill) => (
                                <tr key={bill._id} className="table-row">
                                    <td className="table-cell table-cell-left">{bill._id.substring(0, 8)}...</td>
                                    <td className="table-cell table-cell-left">{bill.tableNumber}</td>
                                    <td className="table-cell table-cell-left">{bill.customerName}</td>
                                    <td className="table-cell table-cell-left">{new Date(bill.createdAt).toLocaleDateString()}</td>
                                    <td className="table-cell table-cell-right">${bill.totalWithoutTax.toFixed(2)}</td>
                                    <td className="table-cell table-cell-right">{bill.gstPercentage}%</td>
                                    <td className="table-cell table-cell-right table-cell-bold">${bill.totalAmount.toFixed(2)}</td>
                                    <td className="table-cell table-cell-center">{bill.generatedBy?.name || 'N/A'} ({bill.generatedBy?.role || 'N/A'})</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
};

export default BillHistory;